spring:
  application:
    name: readict
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        format_sql: true
    #        use_sql_comments: true
    hibernate:
      ddl-auto: update
  cache:
    type: caffeine
#server:
#  servlet:
#    context-path: /api
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
